### ISSUE TITLE
Arrays.js Map Function Bug

### ISSUE THREAD

**Issue by StevieIsmagic** [bloominstituteoftechnology/JavaScript-I-Stretch-Assignment#235]
I notice that in arrays.js, test #3 of the 'map' function passes (without any work being done for that problem) once the 'each' function has been successfully completed. 
![image](https://user-images.githubusercontent.com/6904316/36504784-a856f46e-171f-11e8-9d95-bf86e835688d.png)

**Comment by ryan-hamblin** [comment]
Thanks Steve. This issue is now fixed. The test was testing `each` and not `map` Closing this ticket.

**Comment by 29shubham29** [comment]
Hey how to invoke these functions?
